USE WAREHOUSE COMPUTE_WH;
USE ROLE accountadmin;
CREATE OR REPLACE DATABASE {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DB;
CREATE SCHEMA IF NOT EXISTS {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DB.TEST;
CREATE or replace STAGE {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DB.TEST.QUICKSTART 
DIRECTORY = (ENABLE = TRUE);

GRANT OWNERSHIP ON STAGE {{ env.DATAOPS_PREFIX }}_DB.TEST.QUICKSTART 
TO ROLE public COPY CURRENT GRANTS;

CREATE OR REPLACE TABLE {{ env.DATAOPS_PREFIX }}_DB.TEST.TEST_OPERATIONS(KEY STRING, VALUE STRING);

INSERT INTO {{ env.DATAOPS_PREFIX }}_DB.TEST.TEST_OPERATIONS
VALUES
('INSTALL_DB','INSTALL_TEST'),
('ADMIN_SCHEMA','TEST'),
('OPS_SCHEMA','TEST'),
('RESULT_SCHEMA','TEST'),
('INSTALL_STAGE','QUICKSTART'),
('OPS_WH','COMPUTE_WH');


PUT file:///{{ env.CI_PROJECT_DIR }}/scripts/install.ipynb @{{ env.DATAOPS_PREFIX }}_DB.TEST.QUICKSTART/ auto_compress = false overwrite = true;


CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_PREFIX }}_DB.TEST.TEST_SOLUTION_INSTALL
FROM '@{{ env.DATAOPS_PREFIX }}_DB.TEST.QUICKSTART/'
MAIN_FILE = 'install.ipynb'
QUERY_WAREHOUSE = 'COMPUTE_WH';

ALTER NOTEBOOK {{ env.DATAOPS_PREFIX }}_DB.TEST.TEST_SOLUTION_INSTALL ADD LIVE VERSION FROM LAST;

EXECUTE NOTEBOOK {{ env.DATAOPS_PREFIX }}_DB.TEST.TEST_SOLUTION_INSTALL();
