USE ROLE accountadmin;
CREATE OR REPLACE DATABASE INSTALL_TEST;
CREATE SCHEMA IF NOT EXISTS TEST;
CREATE or replace STAGE INSTALL_TEST.TEST.QUICKSTART 
DIRECTORY = (ENABLE = TRUE);

GRANT OWNERSHIP ON STAGE INSTALL_TEST.TEST.QUICKSTART 
TO ROLE public COPY CURRENT GRANTS;

PUT file:///snowflake/solutions/snowflake-labs-emerging-solutions-toolbox-63f264/solution/* @INSTALL_TEST.TEST.QUICKSTART/ auto_compress = false overwrite = true;
